### PR TITLE
Don't assume a null s_driver in module ctor

### LINKED ISSUE #178: Possible s_driver leaking path
This came up while investigating https://github.com/bosagora/agora/issues/1480

For DNS lookups `vibe.d` is spawning threads and this results in multiple calls to ctor and dtor below.

https://github.com/vibe-d/eventcore/blob/d070fef3afe21dbeb75251cd5c95bfa54798b3d9/source/eventcore/core.d#L34-L53

The problem is the assumption at L38, which is not always true. When module ctors are being run, they can trigger a call to `eventDriver` which then creates a driver instance. In our case this was a Timer dtor triggered by a GC cycle which was triggered by an allocation in one of our module ctors.

Once that assertion fails, the newly created thread is terminated and the module dtor for `core.d` is never called. That causes `s_driver` and all the heap allocated stuff with it to be leaked every once in a while. But this is common enough to crash our application in a couple of days time span.

Where do you suggest this should be resolved? Do you think the module dtors should be called even if a module ctor throws an exception?

### PR DESCRIPTION
**Pull request by omerfirmak**
Fixes #178

### CODE REVIEW

File: source/eventcore/drivers/posix/select.d [hunk 1]
```diff
@@ -79,6 +79,7 @@ final class SelectEventLoop : PosixEventLoop {
 
 	override void dispose()
 	{
+		super.dispose();
 	}
```
Comment (Geod24) [inline source/eventcore/drivers/posix/select.d:83]: In this case, just remove the override ? But it looks like this is no accident ?

Comment (omerfirmak) [reply source/eventcore/drivers/posix/select.d:83]: Yep, so that whoever messes with these next can't miss it.

**Review by Geod24 — APPROVED** [review]
